# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/pipeline

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: CMake@1
  inputs:
    workingDirectory: $(Build.SourcesDirectory)\build\x64-Release-vs2017
    cmakeArgs: ..\.. -G"Visual Studio 16 2019" -A Win64

- task: CMake@1
  inputs:
    workingDirectory: $(Build.SourcesDirectory)\build\x64-Release-vs2017
    cmakeArgs: --build .

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
